apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"repositories":"- name: my-helm-repo   # Specify the repository name here\n  url: https://harbor-core.harbor.svc.cluster.local\n  type: helm           # Change the type to 'helm'\n  username: admin\n  password: Harbor12345\n  insecure: true       # Ensure this is set if using an insecure connection\n","repository.allowInsecure":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-09-29T06:52:58Z","labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd","resourceVersion":"252380","uid":"8d0a48cd-6e47-461f-af1b-ca75997f8c79"}}
  creationTimestamp: "2024-09-29T06:52:58Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "252566"
  uid: 8d0a48cd-6e47-461f-af1b-ca75997f8c79
